Inventory/urls.py
from django.urls import path
from .views import *

from graphene_django.views import GraphQLView
from .schema import schema


urlpatterns = [
    path('', inventory, name='inventory'),
    path('all-products/', all_items_list, name='all_items_list'),
    path('edit/<int:pk>/', product_edit, name='product_edit'),
    path('sales/', sales_list, name='sales_list'),
    path('add-inventory/', add_inventory, name='add_inventory'),

    path("api", GraphQLView.as_view(graphiql=True, schema=schema)),

]

docs/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', docs, name='docs'),
    path('developers/<slug:slug>/', dev, name='dev'),
    path('users/<slug:slug>/', users, name='users'),
    path('System-Administrator/<slug:slug>/', sys_admin, name='sys_admin'),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vercel_app/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.views.static import serve
from vercel_app.utils import export_csv

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    path('', include('Homepage.urls')),
    path('Conditions/', include('conditions.urls')),
    path('Dashboard/', include('example.urls')),
    path('Machine/', include('Machines.urls')),
    path('Resources/', include('Resources.urls')),
    path('docs/', include('docs.urls')),
    path('inventory/', include('Inventory.urls')),

    path('export-csv/', export_csv, name='export_csv'),
    
    re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
]

handler404 = "example.views.page_not_found_view"

Inventory/models.py
import os
from dotenv import load_dotenv
from django.utils.text import slugify
from django.db import models
from django.utils.html import format_html
from supabase import create_client, Client, ClientOptions

load_dotenv()

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
supabase: Client = create_client(url, key,
  options=ClientOptions(
    postgrest_client_timeout=10,
    storage_client_timeout=10
  ))

class BrickCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=255)

    def save(self, *args, **kwargs):
        # If the slug is not set or the name has changed, generate the slug
        if not self.slug or self.name != self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['id']

    @classmethod
    def bulk_create_from_import(cls, data):
        cls.objects.bulk_create([cls(**item) for item in data])


class BrickProduct(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=255)

    category = models.ForeignKey(BrickCategory, on_delete=models.CASCADE)
    description = models.TextField()
    product_image = models.ImageField()
    product_code = models.CharField(max_length=10, unique=True, editable=False)

    def product_img_display(self):
        res = supabase.storage.from_('Products_image/').get_public_url(self.product_image)
        return format_html('<img src="{}" width="100" height="100">', res)
    
    def save(self, *args, **kwargs):
        # If the slug is not set or the name has changed, generate the slug
        if not self.slug or self.name != self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

        if not self.pk:  # Only for new instances
            last_product = BrickProduct.objects.order_by('-id').first()
            if last_product:
                last_code = last_product.product_code
                last_num = int(last_code.split('-')[1])
                new_num = last_num + 1
                self.product_code = f'HB-{str(new_num).zfill(4)}'
            else:
                self.product_code = 'HB-0001'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['id']

    @classmethod
    def bulk_create_from_import(cls, data):
        cls.objects.bulk_create([cls(**item) for item in data])
  
class ProductAttribute(models.Model):
    product = models.ForeignKey(BrickProduct, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    dimensions = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.product.name} of {self.name}"
    
    class Meta:
        ordering = ['id']

    @classmethod
    def bulk_create_from_import(cls, data):
        cls.objects.bulk_create([cls(**item) for item in data])

class Sale(models.Model):
    product = models.ForeignKey(BrickProduct, on_delete=models.CASCADE)
    product_attribute = models.ForeignKey(ProductAttribute, on_delete=models.CASCADE)
    quantity_sold = models.PositiveIntegerField()
    date_sold = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Convert quantity_sold to integer
        quantity_sold = int(self.quantity_sold)
        self.product_attribute.stock -= quantity_sold
        self.product_attribute.save()

    def __str__(self):
        return f"{self.quantity_sold} units of {self.product.name} ({self.product_attribute.name}) sold on {self.date_sold}"
    
    class Meta:
        ordering = ['id']

    @classmethod
    def bulk_create_from_import(cls, data):
        cls.objects.bulk_create([cls(**item) for item in data])



class BrickStock(models.Model):
    product = models.ForeignKey(BrickProduct, on_delete=models.CASCADE)
    quantity_added = models.PositiveIntegerField()
    stock_in_date = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.product.stock += self.quantity_added
        self.product.save()

    def __str__(self):
        return f"{self.quantity_added} units of {self.product.name} added on {self.stock_in_date}"
    
    class Meta:
        ordering = ['id']

    @classmethod
    def bulk_create_from_import(cls, data):
        cls.objects.bulk_create([cls(**item) for item in data])

Inventory/forms.py
from django import forms
from .models import *
from django.forms import inlineformset_factory

class BrickProductForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write short description'}), required=False)
    product_image = forms.ImageField(required=True)

    class Meta:
        model = BrickProduct
        fields = ['name', 'category', 'description', 'product_image']

class ProductAttributeForm(forms.ModelForm):
    class Meta:
        model = ProductAttribute
        fields = ['name','dimensions', 'price', 'stock']
        
class SalesForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = '__all__'


class add_inventoryForm(forms.ModelForm):    
    class Meta:
        model = BrickStock
        fields = '__all__'

Inventory/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone

from django.forms import inlineformset_factory
from .forms import *
from .models import *
from .utils import generate_product_code

# Importing environment variables
import os
from supabase import create_client
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Initialize Supabase client
url = os.environ.get('SUPABASE_URL')
key = os.environ.get('SUPABASE_SERVICE_ROLE_KEY')
supabase = create_client(url, key)

@login_required(login_url='login')
def inventory(request):
    """
    View for managing inventory.

    Args:
        request: HttpRequest object.

    Returns:
        Rendered template for inventory management with context data.
    """
    # Check if the user is a superuser
    if not request.user.is_superuser:
        return HttpResponseForbidden("You don't have permission to access this page.")

    # Fetch all categories
    categories = BrickCategory.objects.all()

    # Define inline formset for product attributes
    ProductAttributeFormSet = inlineformset_factory(BrickProduct, ProductAttribute, form=ProductAttributeForm, extra=1)

    if request.method == 'POST':
        form = BrickProductForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the new product
            new_product = form.save(commit=False)
            new_product.product_image = new_product.product_image.name
            new_product.product_code = generate_product_code()
            new_product.save()

            # Upload product image to Supabase storage
            supabase.storage.from_('Products_image').upload(new_product.product_image.name, new_product.product_image.read(), {'content-type': 'image/jpeg'})

            # Process product attributes formset
            product_attribute_formset = ProductAttributeFormSet(request.POST, instance=new_product)
            if product_attribute_formset.is_valid():
                product_attribute_formset.save()

                messages.success(request, f"New product {new_product.name} added successfully")
                return redirect('inventory')
        else:
            product_attribute_formset = ProductAttributeFormSet(request.POST)

    else:
        form = BrickProductForm()
        product_attribute_formset = ProductAttributeFormSet()

    context = {
        'form': form,
        'product_attribute_formset': product_attribute_formset,
        'categories': categories,
    }
    return render(request, 'Inventory/add_new_product.html', context)

@login_required(login_url='login')
def all_items_list(request):
    """
    View for displaying all items in inventory.

    Args:
        request: HttpRequest object.

    Returns:
        Rendered template for displaying all items with context data.
    """
    # Check if the user is a superuser
    if not request.user.is_superuser:
        return HttpResponseForbidden("You don't have permission to access this page.")
    
    # Handle search query
    search_query = request.GET.get('search')
    if search_query:
        # Filter items based on search query
        all_items_list = BrickProduct.objects.filter(
            Q(name__icontains=search_query) |
            Q(category__name__icontains=search_query) |
            Q(product_code__icontains=search_query)
        )
    else:
        all_items_list = BrickProduct.objects.all()

    # Convert Decimal objects to float
    product_attributes_json = []
    for brick_product in all_items_list:
        attributes = brick_product.productattribute_set.all().values('name', 'dimensions', 'price', 'stock')
        for attribute in attributes:
            product_attributes_json.append({
                'name': attribute['name'],
                'dimensions': attribute['dimensions'],
                'price': float(attribute['price']),
                'stock': attribute['stock'],
            })

    # Handle Pagination
    paginator = Paginator(all_items_list, 12)  # 12 products per page
    page_number = request.GET.get('page')
    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    form = BrickProductForm(request.POST if request.method == 'POST' else None)

    for brick_product in products:
        # Get public URL for product_image
        res = supabase.storage.from_('Products_image').get_public_url(brick_product.product_image)
        # Update product_image field with the public URL
        brick_product.product_image = res

    context = {
        'all_items': products,
        'product_attributes_json': product_attributes_json,  # Convert to JSON
        'forms': form
    }
    return render(request, 'Inventory/All_product_list.html', context)

@login_required(login_url='login')
def product_edit(request, pk):
    """
    View for editing a product in inventory.

    Args:
        request: HttpRequest object.
        pk: Primary key of the product to be edited.

    Returns:
        Rendered template for product editing with context data.
    """
    # Check if the user is a superuser
    if not request.user.is_superuser:
        return HttpResponseForbidden("You don't have permission to access this page.")

    brick_product = get_object_or_404(BrickProduct, pk=pk)
    ProductAttributeFormSet = inlineformset_factory(BrickProduct, ProductAttribute, fields=('name', 'dimensions', 'price', 'stock'), extra=1)

    if request.method == 'POST':
        form = BrickProductForm(request.POST, instance=brick_product)
        formset = ProductAttributeFormSet(request.POST, instance=brick_product)
        
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('all_items_list')  # Redirect to the list view after editing
    else:
        form = BrickProductForm(instance=brick_product)
        formset = ProductAttributeFormSet(instance=brick_product)

    context = {
        'forms': form,
        'formset': formset,
        'brick_product': brick_product,
    }
    return render(request, 'Inventory/Edit_product_Byid.html', context)

@login_required(login_url='login')
def sales_list(request):
    """
    View for managing sales.

    Args:
        request: HttpRequest object.

    Returns:
        Rendered template for managing sales with context data.
    """
    # Check if the user is a superuser
    if not request.user.is_superuser:
        return HttpResponseForbidden("You don't have permission to access this page.")
    
    form =SalesForm()
    sale = Sale.objects.all()
    products = BrickProduct.objects.all()
    product_attributes = ProductAttribute.objects.all()

    if request.method == 'POST':
        form = SalesForm(request.POST)
        if form.is_valid():
            # Get data from form
            f_product_id = request.POST.get('product')
            f_product_attribute_name = request.POST.get('product_attribute')
            f_quantity_sold = request.POST.get('quantity_sold')
            
            # Retrieve product and filter product attribute by product_id and name
            f_product = BrickProduct.objects.get(id=f_product_id)
            f_product_attribute = get_object_or_404(ProductAttribute, product_id=f_product_id, name=f_product_attribute_name)

            # Create new sales entry
            new_sales = Sale.objects.create(
                product=f_product,
                product_attribute=f_product_attribute.id,
                quantity_sold=f_quantity_sold,
                date_sold=timezone.now(),
            )
            new_sales.save()
            return redirect('all_items_list')  # Redirect to the list view after editing
    else:
        form = SalesForm()
    context ={
        "forms":form,
        "sales":sale,
        "products": products,
        "product_attributes": product_attributes,
    }
    return render(request, 'Inventory/Sales_list_add.html', context)

@login_required(login_url='login')
def add_inventory(request):
    """
    View for adding inventory.

    Args:
        request: HttpRequest object.

    Returns:
        Rendered template for adding inventory with context data.
    """
    if not request.user.is_superuser:
        return HttpResponseForbidden("You don't have permission to access this page.")

    form =add_inventoryForm()
    add_inventory = BrickStock.objects.all()

    if request.method == 'POST':
        form = add_inventoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('add_inventory')  # Redirect to the list view after editing
    else:
        form = add_inventoryForm()
    context ={
        "forms":form,
        "added_inventory":add_inventory,

    }
    return render(request, 'Inventory/Add_inventory.html', context)

templates/Inventory/Edit_product_Byid.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} Edit product | hirabricks {% endblock %} 

{% block content %}
<div class="border border-gray-300 shadow-lg bg-white rounded-xl p-3 sm:p-7 dark:bg-slate-900">
    <div class="border-b border-gray-100 px-6 py-4">
        <h3 class="font-medium text-gray-600 dark:text-gray-400">Edit product</h3>
    </div>

    <form class="mx-auto px-12 py-12" action="{% url 'product_edit' pk=brick_product.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-5">
            {{ forms.as_p }}
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form.as_p }}
            {% endfor %}    
        </div>
        <button type="submit" class="mt-4 w-full rounded-lg bg-primary px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-primary focus:outline-none focus:ring-4 focus:ring-red-300 sm:w-auto dark:bg-primary dark:hover:bg-primary dark:focus:ring-primary">Submit</button>
        {% for message in messages %}
            <p id="bg-green-500 px-4 py-6">{{message}}</p>
        {% endfor %}
    </form>
    
</div>

{% endblock content %}

templates/Inventory/add_new_product.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} Inventory | hirabricks {% endblock %} 

{% block content %}

<div class="rounded-xl border border-gray-300 bg-white p-3 shadow-lg sm:p-7 dark:bg-slate-900">
  <div class="border-b border-gray-100 px-6 py-4">
    <h3 class="font-medium text-gray-600 dark:text-gray-400">Product Form</h3>
  </div>
  <form class="mx-auto px-12 py-12" action="{% url 'inventory' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-5">
      <div>
        <label for="id_name" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Name:</label>
        <input type="text" name="name" maxlength="100" required="" id="id_name" class="focus:border-primary focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 sm:text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" />
      </div>

      <div>
        <label for="id_category" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Category:</label>
        <select name="category" required="" id="id_category" class="focus:border-primary focus:ring-primary dark:focus:border-primary dark:focus:ring-primary block w-full cursor-pointer rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400">
          <option value="" selected="" class="ml-2 text-left text-sm font-medium text-gray-900">---------</option>
          {% for category in categories %}
          <option value="{{ category.id }}" class="ml-2 text-left text-sm font-medium text-gray-900">{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>
      <div>
        <label for="id_product_image" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Product image:</label>
        <input type="file" name="product_image" accept="image/*" required="" id="id_product_image" class="focus:border-primary focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 sm:text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" />
      </div>
      <div>
        <label for="id_description" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Description:</label>
        <textarea name="description" cols="40" rows="10" placeholder="Write short description" id="id_description" class="focus:border-primary focus:ring-primary dark:focus:border-primary dark:focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400"></textarea>
      </div>
    </div>

    {{ product_attribute_formset.management_form }}
    <div class="product-attribute-formset" id="attribute-formset-wrapper">
        {% for form in product_attribute_formset %}
            <div class="product-attribute-form">
                {{ form.as_table }}
            </div>
        {% endfor %}
    </div>
    
    <button type="button" id="add-attribute-formset" class="bg-primary hover:bg-secondary dark:bg-primary dark:hover:bg-primary dark:focus:ring-secondary mt-4 w-full rounded-lg px-5 py-2.5 text-center text-sm font-medium text-white focus:outline-none focus:ring-4 focus:ring-red-300 sm:w-auto">Add Attribute</button>

    <button type="submit" class="bg-primary hover:bg-secondary dark:bg-primary dark:hover:bg-primary dark:focus:ring-secondary mt-4 w-full rounded-lg px-5 py-2.5 text-center text-sm font-medium text-white focus:outline-none focus:ring-4 focus:ring-red-300 sm:w-auto">Submit</button>
    </form>

  
</div>
<!-- JavaScript for dynamically adding/removing formsets -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
      const formsetWrapper = document.getElementById('attribute-formset-wrapper');

      let formsetIndex = 0;

      function addFormset() {
          const formsetHTML = `<div class="formset" id="formset-${formsetIndex}">
              <!-- Your attribute form fields -->
          </div>`;
          formsetWrapper.insertAdjacentHTML('beforeend', formsetHTML);
          formsetIndex++;
      }

      function removeFormset(formsetID) {
          const formset = document.getElementById(formsetID);
          formset.remove();
      }

      // Using event delegation for dynamically added button
      document.addEventListener('click', function(event) {
          if (event.target && event.target.id === 'add-attribute-formset') {
              addFormset();
          }
      });
  });
</script>


{% endblock content %}

templates/Inventory/productForms.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} Inventory | hirabricks {% endblock %} 

{% block content %}
<div class="rounded-xl border border-gray-300 bg-white p-3 shadow-lg sm:p-7 dark:bg-slate-900">
  <div class="border-b border-gray-100 px-6 py-4">
    <h3 class="font-medium text-gray-600 dark:text-gray-400">Add product</h3>
  </div>
  {% for message in messages %}
  <div class="pt-4" x-data="{ isOpen: true }">
    <div class="border-stroke dark:border-dark-3 dark:bg-dark-2 mb-11 flex items-center rounded-md border border-l-[8px] border-l-[#00B078] bg-white p-5 pl-8" x-show="isOpen">
      <div class="mr-5 flex h-[36px] w-full max-w-[36px] items-center justify-center rounded-full bg-[#00B078]">
        <i class="ri-check-fill"></i>
      </div>
      <div class="flex w-full items-center justify-between">
        <div>
          <h3 class="text-dark mb-1 text-lg font-medium dark:text-white">{{message}}</h3>
        </div>
        <div>
          <button class="hover:text-danger text-[#ACACB0]" @click="isOpen = false">
            <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M6 18L18 6M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <form class="mx-auto px-12 py-12" action="{% url 'inventory' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-5">
      <div>
        <label for="id_name" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Name:</label>
        <input type="text" name="name" maxlength="100" required="" id="id_name" class="focus:border-primary focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 sm:text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" />
      </div>

      <div>
        <label for="id_category" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Category:</label>
        <select name="category" required="" id="id_category" class="focus:border-primary focus:ring-primary dark:focus:border-primary dark:focus:ring-primary block w-full cursor-pointer rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400">
          <option value="" selected="" class="ml-2 text-left text-sm font-medium text-gray-900">---------</option>
          {% for category in categories %}
          <option value="{{ category.id }}" class="ml-2 text-left text-sm font-medium text-gray-900">{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div>
          <label for="id_price" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Price:</label>
          <input type="number" name="price" value="0" required="" id="id_price" class="focus:border-primary focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 sm:text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" />
        </div>

        <div>
          <label for="id_stock" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Stock:</label>
          <input type="number" name="stock" value="0" min="0" required="" id="id_stock" class="focus:border-primary focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 sm:text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" />
        </div>
      </div>
      <div>
        <label for="id_dimensions" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Dimensions:</label>
        <input type="text" name="dimensions" placeholder="Provide dimensions of Brick" id="id_dimensions" class="focus:border-primary focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 sm:text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" />
      </div>
      <div>
        <label for="id_product_image" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Product image:</label>
        <input type="file" name="product_image" accept="image/*" required="" id="id_product_image" class="focus:border-primary focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 sm:text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" />
      </div>
      <div>
        <label for="id_description" class="mb-2 mt-4 block text-sm font-medium text-gray-900 dark:text-white">Description:</label>
        <textarea name="description" cols="40" rows="10" placeholder="Write short description" id="id_description" class="focus:border-primary focus:ring-primary dark:focus:border-primary dark:focus:ring-primary block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400"></textarea>
      </div>
    </div>
    <button type="submit" class="bg-primary hover:bg-secondary dark:bg-primary dark:hover:bg-primary dark:focus:ring-secondary mt-4 w-full rounded-lg px-5 py-2.5 text-center text-sm font-medium text-white focus:outline-none focus:ring-4 focus:ring-red-300 sm:w-auto">Submit</button>
  </form>
</div>

{% endblock content %}